"""update introduce

Revision ID: 2ed742d62efa
Revises: 703ebd28de1f
Create Date: 2023-02-03 16:45:35.646463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ed742d62efa'
down_revision = '703ebd28de1f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('introduction', sa.String(), server_default='hello world', nullable=False, comment='自我介紹'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'introduction')
    # ### end Alembic commands ###
