"""test update column attribute

Revision ID: 41e1eda141eb
Revises: 44779d44ab63
Create Date: 2023-02-03 16:50:42.243913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41e1eda141eb'
down_revision = '44779d44ab63'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.alter_column( 'introduction',
                   existing_type=sa.VARCHAR(),
                   nullable=False,
                   existing_server_default=sa.text("'hello world'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('members', 'introduction',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'hello world'"))
    # ### end Alembic commands ###
