"""test update column attribute

Revision ID: 4313a9e54310
Revises: 41e1eda141eb
Create Date: 2023-02-06 16:41:34.716658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4313a9e54310'
down_revision = '41e1eda141eb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('member_id', sa.String(), nullable=True))
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'members', ['member_id'], ['id'])
    op.drop_column('messages', 'member_username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('member_username', sa.VARCHAR(), nullable=True))
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'members', ['member_username'], ['username'])
    op.drop_column('messages', 'member_id')
    # ### end Alembic commands ###
