"""update introduce

Revision ID: 44779d44ab63
Revises: 2ed742d62efa
Create Date: 2023-02-03 16:45:57.574486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44779d44ab63'
down_revision = '2ed742d62efa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.alter_column( 'introduction',
                   existing_type=sa.VARCHAR(),
                   nullable=True,
                   existing_server_default=sa.text("'hello world'"))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('members', 'introduction',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'hello world'"))
    # ### end Alembic commands ###
