"""update introduce

Revision ID: 703ebd28de1f
Revises: 8a1741165554
Create Date: 2023-02-03 16:44:54.655337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '703ebd28de1f'
down_revision = '8a1741165554'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'introduction')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('introduction', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
