"""Member add introduction

Revision ID: 8a1741165554
Revises: a82e38597f84
Create Date: 2023-02-03 15:48:27.329969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a1741165554'
down_revision = 'a82e38597f84'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('introduction', sa.String(), nullable=True, comment='自我介紹'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'introduction')
    # ### end Alembic commands ###
