# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Create and publish a Docker image

env:
  AZURE_WEBAPP_NAME: ford-amd   # set this to your application's name
on:
  push:
    branches: ['main']
permissions:
  contents: 'read'
  packages: 'write'

jobs:
  build:
    environment: 
      name: prod
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      Greeting: Hello
    
    steps:
      - name: READ vaialbe test
        run : | 
          echo '$read_my_name'
          echo ${{ env.read_my_name}}
          echo ${{ env.READ_MY_NAME }}
          echo $READ_MY_NAME
          echo $Greeting
          echo ${{ vars.READ_MY_NAME }}
          echo ${{ secrets.HELLO }}
          
          
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Lowercase the repo name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
#      - name: Build and push container image to registry
#        uses: docker/build-push-action@v2
#        with:
#          push: true
#          tags: ghcr.io/${{ env.REPO }}:${{ github.sha }}
#          file: ./Dockerfile
      - uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: ${{ env.REPO }}
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
          tag: ${{ github.sha }},latest
          multiPlatform: true
          platform: linux/amd64,linux/arm/v7
  deploy:
    runs-on: ubuntu-latest

    needs: build

    environment:
      name: prod
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Lowercase the repo name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@0b651ed7546ecfc75024011f76944cb9b381ef1e
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: 'ghcr.io/${{ env.REPO }}:${{ github.sha }}'
#  prod-check:
#    if: ${{ github.ref == 'refs/heads/main' }}
#    runs-on: ubuntu-latest
#    steps:
#      - run: echo "Deploying to production server on branch $GITHUB_REF"


