name: CI

on:
  push:
    branches: [main]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    environment: ford
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.11

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Use variables
      run: |
        echo "repository variable : ${{ vars.HELLO }}"
    - name : build and push
      run: |
        docker build -t ghcr.io/suyuying/fastapi-backend:1.0 .
        docker push ghcr.io/suyuying/fastapi-backend:1.0
        docker ps
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/${{ github.repository_name }}/my-image:latest
